### ISSUE TITLE
Not rendering on iOS 16

### ISSUE THREAD

**Issue by fekberg** [ewerspej/epj.ProgressBar.Maui#1]
Downloaded the sample code, built it and ran it on an iOS device with iOS 16.3.1 and it doesn't show any of the progress bars.

**Comment by ewerspej** [comment]
I tried to reproduce the issue on an iPhone 8 running iOS 16.3.1 and couldn't reproduce the issue, it works well for me. Can you provide more details?

**Comment by ewerspej** [comment]
Hi @fekberg , did you manage to run the sample in the meanwhile? Does the issue still occur?

**Comment by ewerspej** [comment]
@fekberg Haven't heard back from you on this yet. I've not encountered the problem you're describing.

**Comment by fekberg** [comment]
I was running it on an iPhone 14 with that iOS version, which is now iOS 17.

Sorry, haven't been working on the project for a while and can't remember what I did on iOS. I think it was due to the control being wrapped in another control, or something like that. If I see it again I will let you know.

**Comment by ewerspej** [comment]
@fekberg OK. You can also tell me at Techorama next month 😉
