### ISSUE TITLE
Use Microsoft.Maui.Graphics instead of SkiaSharp

### ISSUE THREAD

**Issue by tranb3r** [ewerspej/epj.ProgressBar.Maui#4]
Hi,
Are you planning on migrating from SkiaSharp to Microsoft.Maui.Graphics?
Thanks.

**Comment by tranb3r** [comment]
SkiaSharp is really big. For such a simple control, I'm not sure it's the best choice.

**Comment by ewerspej** [comment]
I get the point. I suppose that will change when full Native AOT support becomes available.

MAUI Graphics works well with static graphics, but drawing a control based on constantly changing data via bindings works better with Skia, in my experience.
