### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by marosklempa** [ewerspej/epj.ProgressBar.Maui#5]
Could be possible to add property which will round the progress bar corners? Simillar like MAUI border do.

<Border Stroke="Black" StrokeThickness="1" BackgroundColor="DarkGray" HeightRequest="25">
    <Border.StrokeShape>
        <RoundRectangle CornerRadius="2,2,2,2" />
    </Border.StrokeShape>
</Border>

Thanks
Maroš

**Comment by ewerspej** [comment]
If you just need rounded corners on the outside, you could wrap the control with a Border with rounded corners, e.g.:

```xml
<Border
    StrokeShape="RoundedRectangle 8"
    Stroke="Transparent"
    StrokeWidth="0">
    <epj:ProgressBar />
</Border>
```

I'm already considering adding this as a feature for the progress indicator bar.

**Comment by marosklempa** [comment]
Thanks, that workaround works well, solve my problem.

**Comment by ewerspej** [comment]
I added an option to have rounded caps, you can enable it by setting `RoundCaps="True"`. It's currently available as a prerelease (https://www.nuget.org/packages/epj.ProgressBar.Maui/1.0.2-pre), so be sure to tick the "include prerelease" checkbox in the package manager.

**Comment by marosklempa** [comment]
Thanks, I will test it.
